DEFINE TABLESPACE_NAME=&&1;
DEFINE TBS_TYPE=&&2;

DROP TABLESPACE &&TABLESPACE_NAME._&&TBS_TYPE
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

UNDEFINE TABLESPACE_NAME;
UNDEFINE TBS_TYPE;