TRUNCATE TABLE ALBUMS;
TRUNCATE TABLE USERS;
TRUNCATE TABLE STYLES;
TRUNCATE TABLE PLAYLISTS;
TRUNCATE TABLE COMPOSITIONS;
TRUNCATE TABLE USER_STATUSES;
TRUNCATE TABLE LISTENING_HISTORIES;
TRUNCATE TABLE COMPOSITION_REVIEWS;
TRUNCATE TABLE PLAYLIST_CONTENTS;
TRUNCATE TABLE ALBUM_REVIEWS;

DELETE FROM USERS;
DELETE FROM STYLES;