DEFINE USER_NAME = &&1
DEFINE INDEX_TABLESPACE = '&&USER_NAME._IDX'

ALTER TABLE USERS ADD CONSTRAINT PK_USER PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE ALBUMS ADD CONSTRAINT PK_ALBUM PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE STYLES ADD CONSTRAINT PK_STYLE PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE PLAYLISTS ADD CONSTRAINT PK_PLAYLIST PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE COMPOSITIONS ADD CONSTRAINT PK_COMPOSITION PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE USER_STATUSES ADD CONSTRAINT PK_USER_STATUS PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE LISTENING_HISTORIES ADD CONSTRAINT PK_LISTENING_HISTORY PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE COMPOSITION_REVIEWS ADD CONSTRAINT PK_COMPOSITION_REVIEW PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE PLAYLIST_CONTENTS ADD CONSTRAINT PK_PLAYLIST_CONTENT PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE ALBUM_REVIEWS ADD CONSTRAINT PK_ALBUM_REVIEW PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE USER_STATUSES ADD CONSTRAINT FK_USER_STATUSES_USER FOREIGN KEY(User_ID) REFERENCES USERS(ID) ON DELETE CASCADE;
CREATE INDEX FK_USER_STATUSES_USER ON USER_STATUSES(User_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE USER_STATUSES ADD CONSTRAINT FK_USER_STATUSES_ALBUM FOREIGN KEY(Current_Album_ID) REFERENCES ALBUMS(ID) ON DELETE CASCADE;
CREATE INDEX FK_USER_STATUSES_ALBUM ON USER_STATUSES(Current_Album_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE USER_STATUSES ADD CONSTRAINT FK_USER_STATUSES_COMPOSITION FOREIGN KEY(Current_Composition_ID) REFERENCES COMPOSITIONS(ID) ON DELETE CASCADE;
CREATE INDEX FK_USER_STATUSES_COMPOSITION ON USER_STATUSES(Current_Composition_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE COMPOSITION_REVIEWS ADD CONSTRAINT FK_COMPOSITION_REVIEWS_COMPOSITION FOREIGN KEY(Composition_ID) REFERENCES COMPOSITIONS(ID) ON DELETE CASCADE;
CREATE INDEX FK_COMPOSITION_REVIEWS_COMPOSITION ON COMPOSITION_REVIEWS(Composition_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE COMPOSITION_REVIEWS ADD CONSTRAINT FK_COMPOSITION_REVIEWS_USER FOREIGN KEY(USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;
CREATE INDEX FK_COMPOSITION_REVIEWS_USER ON COMPOSITION_REVIEWS(USER_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE ALBUM_REVIEWS ADD CONSTRAINT FK_ALBUM_REVIEWS_ALBUM FOREIGN KEY(ALBUM_ID) REFERENCES ALBUMS(ID) ON DELETE CASCADE;
CREATE INDEX FK_ALBUM_REVIEWS_ALBUM ON ALBUM_REVIEWS(ALBUM_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE ALBUM_REVIEWS ADD CONSTRAINT FK_ALBUM_REVIEWS_USER FOREIGN KEY(USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;
CREATE INDEX FK_ALBUM_REVIEWS_USER ON ALBUM_REVIEWS(USER_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE COMPOSITIONS ADD CONSTRAINT FK_COMPOSITIONS_OWNER FOREIGN KEY(OWNER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;
CREATE INDEX FK_COMPOSITIONS_OWNER ON COMPOSITIONS(OWNER_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE COMPOSITIONS ADD CONSTRAINT FK_COMPOSITIONS_STYLE FOREIGN KEY(STYLE_ID) REFERENCES STYLES(ID) ON DELETE CASCADE;
CREATE INDEX FK_COMPOSITIONS_STYLE ON COMPOSITIONS(STYLE_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE COMPOSITIONS ADD CONSTRAINT FK_COMPOSITIONS_ALBUM FOREIGN KEY(ALBUM_ID) REFERENCES ALBUMS(ID) ON DELETE CASCADE;
CREATE INDEX FK_COMPOSITIONS_ALBUM ON COMPOSITIONS(ALBUM_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE PLAYLIST_CONTENTS ADD CONSTRAINT FK_PLAYLIST_CONTENTS_PLAYLIST FOREIGN KEY(PLAYLIST_ID) REFERENCES PLAYLISTS(ID) ON DELETE CASCADE;
CREATE INDEX FK_PLAYLIST_CONTENTS_PLAYLIST ON PLAYLIST_CONTENTS(PLAYLIST_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE PLAYLIST_CONTENTS ADD CONSTRAINT FK_PLAYLIST_CONTENTS_COMPOSITION FOREIGN KEY(COMPOSITION_ID) REFERENCES COMPOSITIONS(ID) ON DELETE CASCADE;
CREATE INDEX FK_PLAYLIST_CONTENTS_COMPOSITION ON PLAYLIST_CONTENTS(COMPOSITION_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE PLAYLISTS ADD CONSTRAINT FK_PLAYLISTS_OWNER FOREIGN KEY(OWNER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;
CREATE INDEX FK_PLAYLISTS_OWNER ON PLAYLISTS(OWNER_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE LISTENING_HISTORIES ADD CONSTRAINT FK_LISTENING_HISTORIES_COMPOSITION FOREIGN KEY(COMPOSITION_ID) REFERENCES COMPOSITIONS(ID) ON DELETE CASCADE;
CREATE INDEX FK_LISTENING_HISTORIES_COMPOSITION ON LISTENING_HISTORIES(COMPOSITION_ID) TABLESPACE &&INDEX_TABLESPACE;

UNDEFINE INDEX_TABLESPACE;