DEFINE USER_NAME = &&1
DEFINE DATA_TBS = '&&USER_NAME._DATA'

CREATE TABLE LISTENING_HISTORIES (
	ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	LISTEN_DATE VARCHAR2(100) NOT NULL,
	COMPOSITION_ID NUMBER
)
TABLESPACE &&DATA_TBS;