DEFINE USER_NAME = &&1
DEFINE DATA_TBS = '&&USER_NAME._DATA'

CREATE TABLE USERS (
	ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	NICKNAME VARCHAR2(100) NOT NULL,
	FIRSTNAME VARCHAR2(100),
	LASTNAME VARCHAR2(100),
	EMAIL VARCHAR2(100)
)
TABLESPACE &&DATA_TBS;