DEFINE USER_NAME = &&1
DEFINE DATA_TBS = '&&USER_NAME._DATA'

CREATE TABLE ALBUMS (
	ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	LIKES_NUMBER NUMBER,
	PLAYS_NUMBER NUMBER,
	RATING NUMBER
)
TABLESPACE &&DATA_TBS;