CREATE VIEW result AS 
SELECT 
    u.FIRSTNAME USER_FIRST_NAME,
    u.LASTNAME USER_LAST_NAME,
    u.NICKNAME USER_NICKNAME,
    u.EMAIL USER_EMAIL,
    p.PLAYLIST_NAME PLAYLIST_NAME,
    s.NAME STYLE_NAME,
    c.COMPOSITION_NAME COMPOSITION_NAME,
    c.DURATION COMPOSITION_DURATION,
    c.LIKES COMPOSITION_LIKES,
    c.PLAYS COMPOSITION_PLAYS,
    cr.REVIEW COMPOSITION_REVIEW,
    us.PAUSED USER_STATUS_PAUSED
FROM USERS u
join PLAYLISTS p on p.ID = u.ID
join USER_STATUSES us on u.ID = us.USER_ID
join COMPOSITIONS c on c.ID = us.CURRENT_COMPOSITION_ID
join COMPOSITION_REVIEWS cr on c.ID = cr.COMPOSITION_ID
join STYLES s on c.STYLE_ID = s.ID;

commit;